kind: Service
apiVersion: v1
metadata:
  name: nginx-service-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service-cluster-ip
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service-node-port
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80