apiVersion: v1
kind: Pod
metadata:
  name: nginx-pvc
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - name: volume-pvc
      mountPath: /usr/share/nginx/html
  volumes:
    - name: volume-pvc
      persistentVolumeClaim:
        claimName: volume-pvc