apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    env:
    - name: SECRET_OPAQUE
      valueFrom:
        secretKeyRef:
          name: secret-opaque
          key: extra
    ports:
    - containerPort: 80
    volumeMounts:
    - name: tls-volume
      mountPath: /var/data/tls
  volumes:
    - name: tls-volume
      secret:
        secretName: secret-tls
