apiVersion: v1
kind: Secret
metadata:
  name: secret-sa
  annotations:
    kubernetes.io/service-account.name: default
type: kubernetes.io/service-account-token
data:
  extra: YmFyCg==
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-opaque
type: opaque
data:
  extra: SGVsbG8gd29ybGQK
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-tls
type: kubernetes.io/tls
data:
  # the data is abbreviated in this example
  tls.crt: |
    MIIDlzCCAn+gAwIBAgIUL96s+TfHexTFgvCKdj9cGNyKuGswDQYJKoZIhvcNAQELBQAwWzELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAk1BMQ8wDQYDVQQHDAZCb3N0b24xDTALBgNVBAoMBEFjbWUxCzAJBgNVBAsMAklUMRIwEAYDVQQDDAlsb2NhbGhvc3QwHhcNMjEwNzEwMTMxODI3WhcNMjIwNzEwMTMxODI3WjBbMQswCQYDVQQGEwJVUzELMAkGA1UECAwCTUExDzANBgNVBAcMBkJvc3RvbjENMAsGA1UECgwEQWNtZTELMAkGA1UECwwCSVQxEjAQBgNVBAMMCWxvY2FsaG9zdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKyHaw4xHFAEN1Wl2ruOy6linf4wNCJCgv+OO99xTQX80crque8ivFl66iAyjcjLOB23Qk1qoHOinNp8iPl2OeV4dZ1mWpm8t+kAiY1kvBWQ3+6D3/KtWoAuargwyoYw6k4i/lVnHYzNPgHF7+l5kY1AXC9IPApGdlUnG4KF7Fzk8LtGsoM32UA87GAqJKNukbUR1Ksg3Jyk4EqeMxMicqNBd2iuTRAKADpVx9GwG5zwuJU+OEyEnn02QuSSv6QxRP5zciBoV4doAqFEQ5ADDOkhT6gFnDuEOdoJEBneX8xwXRVjETyUjBD3UigMkcSD+RJGE0BFOu5VgKQLi0UUwI8CAwEAAaNTMFEwHQYDVR0OBBYEFEoZq7Uu3it0cb6ssfzPlZ1oxbMLMB8GA1UdIwQYMBaAFEoZq7Uu3it0cb6ssfzPlZ1oxbMLMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAG6KhHGbR7+5IQe99eBuTjdVWvjXyPRuP/5pX50cFdBSm1PSTHwZiS28q1DyTZiN0bJzZSo0CSam+grIf7i9OtfvSuAyQnu5eDyTiFJO7T8R9dEFmfPH6tsRxWJU9/4F+H4S84SLX47dG6q+4UCaMbRsHS8moNg5C/nqT7GFdbPPZFie61bMvW6hIzilNHJecfRx9KEDF14HHvjuN6St2AARtlME0v3m9dggVP1A2Lb9ZYqsdncY7vxslooa6XSAw8WEhmTx/OOYsT/UsCxTTwxym/HsMYvrXNEF4zWqb2UV7CSmMRG3IreWuJxTnoMoczzHCNEQvwsUVKlDVpjz4Rk=

  tls.key: |
    MIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQCsh2sOMRxQBDdVpdq7jsupYp3+MDQiQoL/jjvfcU0F/NHK6rnvIrxZeuogMo3Iyzgdt0JNaqBzopzafIj5djnleHWdZlqZvLfpAImNZLwVkN/ug9/yrVqALmq4MMqGMOpOIv5VZx2MzT4Bxe/peZGNQFwvSDwKRnZVJxuChexc5PC7RrKDN9lAPOxgKiSjbpG1EdSrINycpOBKnjMTInKjQXdork0QCgA6VcfRsBuc8LiVPjhMhJ59NkLkkr+kMUT+c3IgaFeHaAKhREOQAwzpIU+oBZw7hDnaCRAZ3l/McF0VYxE8lIwQ91IoDJHEg/kSRhNARTruVYCkC4tFFMCPAgMBAAECggEARgCACHcWtMSxKvgrgtRSgDy6PCuUy53PBx/P3T5ccSR+fuW0YXnnkCrWGhBJBQKnly8HIOA1kBWXrPLApO86WIgCuMWR1zUCLfEA3rTTt7Bbm6w4Tn/V65JpzKhHVCE+wEtkhIRdMgcItLF6QXIJA5XskWaurcCfPLesas4p9BppcGSOEGOxGnUGtH2XbREOV34TtUOuz9UF20LhfuWSO1e2PSniT52uDmnMY4uUvpZSZzYo5QwlBNHbf6wLTwLL3e5U7g4GZaYBxA7GXE4SeP4g/QuX1l2kO3/xPHFR4K1oHXTbwJ3FgB4gGLONQZZ12TGAnCmG8Q4wA9cxV1n1CQKBgQDckoe7JX4q5Wte+5Czd0KmcCH25MVpENVzu4rriQN4XhTTzWlsoe1B5cpxhYtOr2d1EyXseXTNihIBXFImi/nItK/TUCVS8Pwp7voJ9SCj8mPOxJuxVuupm829kcRIr6otjYEaqCUUGLDyBeKIl6Y1J0kmBOgs4er7zIEpJwXXSwKBgQDIPXHbUAmhlmaZ05SK5mhJuiymuPi0BmMIeHaY4gSMpRAggzWOF62lu0dewayhKRScDhv0G6RJvns8WP8JQw6qtrR34vVeh3Tfdr1iCfrAAPfiOny6/1h85oP7d9YFpgJDGrzvPT7SF5sVj9oDlJf973sG9ZVYRP6dgcJYWZ6dTQKBgQDJMXNTVpCuChQVUHwd50PJU3D3ppcXDf7VkRTXYWPj8FUpGS33pAApYrR1Ni3quP4ygSPPfr33GeDwkshwVq+hzoauxmU1MZGholU6rfh28wrtONMXQMS3MeHJ7+NNtcYRxQglS4h+u0LzkECg/UrjIxGK92DcR7oysciCxBCE3wJ/DIPKmepmr7K2tuaCYiwEWJdKMyFcaeP8TIs63lNB9Yhbeay5rCfOso0B6Oox3+CxaQ94r8kKe5FsIlltlyaZxBGnNdb5fu74Xv8M1xPImDd3RqxhH07WOPgvR4g12CSH/6msJUeupXLUPoS/G3ouBbDx/31Z2Cp3v2BcxSjUwQKBgA+oCCRxCnfz3FpiEo0vdKCKGEaihpQxvm74J4DzXft9aZhH6qgabGterM5T7coM8OehypIjg+ylN8s0D1S1G7xwI2LhAyu/WcZQpGgN3iqcBRscwd+bWc6opbGCak96hVcYi/BDBhG6tIDE4XhguPTHK6ZOlf4yxW/xX3EyTe0N

