apiVersion: v1
kind: Service
metadata:
  name: loadbalancing
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  clusterIP: 10.100.46.100
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.49.2