apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html
  volumes:
    - name: html-volume
      configMap:
        name: index-html
